Added stat service
pavlovAndrei/java-explore-with-me pull request #1
Opened 2023-02-16 08:25 UTC by pavlovAndrei

2023-02-17 18:57 UTC, EugeneLenkevich requested changes
Привет, Андрей, спасибо за PR

В целом все отлично :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

2023-02-17 18:57 UTC, EugeneLenkevich commented on ewm-stats/dto/src/main/java/ru/practicum/ewm/EndpointHitPost.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
Давай попробуем настроить фоматы даты и времени глобально, чтобы не приходилось вот так везде аннотациями это указывать :)

https://www.baeldung.com/spring-boot-formatting-json-dates

2023-02-17 18:57 UTC, EugeneLenkevich commented on ewm-stats/client/src/main/java/ru/practicum/ewm/ViewStatsClient.java
> +    public ViewStatsClient(@Value("${stats-server.url}") String serverUrl, RestTemplateBuilder builder) {
Вот тут есть моментик, который можно улучшить :)
 
В самом клиенте происходит создание и настройка web-клинента. С архитектурной точки зрения это не очень хорошо, клиент занимается своей настройкой, это не его обязаность. Настройку лучше вынести вовне. Можно сделать конфигурацию для бина web-clients и далее он, настроенный, будет инжектится как и остальные бины.

Единственное, аннотацию @Service надо убрать, вообще, это алтернативный способ объявления бинов: мы можем на класс повесить аннотацию или создать такую вот конфигурацию если требуется провести какую то настройку при создании 

Пример вот, только подправь под свою реализацию

![image](https://user-images.githubusercontent.com/94845100/193436606-1894b4f9-aa6d-4359-adec-0791cef7a4e6.png)


Таким образом мы можем иметь разные настройки клиентов для разных сред: допустим на продакшн-сервере с TLS, сертификатами и пр, на тестововм стенде простое соединение, а для локального запуска мы можем, например, вообще создать заглушку, которая будет возвращать статический текст :)


https://www.baeldung.com/spring-profiles

2023-02-17 18:57 UTC, EugeneLenkevich commented on ewm-stats/service/src/main/java/ru/practicum/ewm/mapper/StatsMapper.java
> +    public static ViewStatsDto toViewStatsDto(ViewStats viewStats) {
Тут наверное static и не нужен :)

2023-02-18 09:21 UTC, pavlovAndrei commented on ewm-stats/service/src/main/java/ru/practicum/ewm/mapper/StatsMapper.java
> +    public static ViewStatsDto toViewStatsDto(ViewStats viewStats) {
Убрал

2023-02-18 09:21 UTC, pavlovAndrei commented on ewm-stats/client/src/main/java/ru/practicum/ewm/ViewStatsClient.java
> +    public ViewStatsClient(@Value("${stats-server.url}") String serverUrl, RestTemplateBuilder builder) {
Добавил конфигурацию

2023-02-18 09:43 UTC, pavlovAndrei commented on ewm-stats/dto/src/main/java/ru/practicum/ewm/EndpointHitPost.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
Евгений, что-то не совсем понимаю, какой из способов из статьи использовать. Конфигурация через application.properties написано, что не работает с Java 8 типами (LoclaDateTime, как у меня)

2023-02-18 10:33 UTC, pavlovAndrei commented on ewm-stats/dto/src/main/java/ru/practicum/ewm/EndpointHitPost.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
В общем, добавил кастомную конфигурацию для Jackson и пропертю для spring с форматом. Так заработало.

2023-02-18 10:36 UTC, pavlovAndrei commented on ewm-stats/dto/src/main/java/ru/practicum/ewm/EndpointHitPost.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
это помогло вообще аннотации для дат убрать из классов dto и контроллера

2023-02-18 16:49 UTC, EugeneLenkevich commented on ewm-stats/dto/src/main/java/ru/practicum/ewm/EndpointHitPost.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
Ну да, в том и суть :)
А как правильно - если работает то и правильно. В принцпе, в проекте у нас могут быть намешаны самые разныне быблиотеки и, соответственно, настраиваться может плюс минус по разному. Потому если работает то и ладно, все библиотеки знать невозможно

2023-02-18 16:50 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-02-18 16:58 UTC, merged