Added Main service
pavlovAndrei/java-explore-with-me pull request #2
Opened 2023-02-21 16:02 UTC by pavlovAndrei

2023-02-21 16:25 UTC, pavlovAndrei commented
Евгений, привет! Если что-то лишнего убрал или где-то напутал - не обессудь, делал задание нон-стоп 24/7, поэтому мозг не всегда индексировал информацию)

2023-02-22 04:38 UTC, EugeneLenkevich commented
Привет, все норм, все это понятно, щас посмотрим )

2023-02-22 04:57 UTC, EugeneLenkevich requested changes
Привет, Андрей, спасибо за PR

В целом все хорошо, единственное, предлоду вот что - посмотреть имена методов сервисов и убрать лишние упоминания сущности. Напрмер, сравни

`usertService.updateUser(user)`
или
`usertService.update(user)`

Второй вариант как то проще читать как мне кажется, как думаешь?
Для контроллеров не так важно, мы эти методы сами напрямую не вызываем в коде =)

Еще подумай, пожалуйста, не слишком ли много try-catch в коде, не портит ли это читаемость кода, может лучше делать обычные проверки кодом перед тем как произвести действие, а потом ловить еще исключение, но это на подумать :)

2023-02-22 04:57 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/category/controller/CategoryAdminController.java
> +    public void deleteCategory(@Positive @PathVariable Long catId) {
@Positive

Наверно можно уж настолько то не заморачиваться, не мешает просто лишняя ж работа :)

2023-02-22 04:57 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/category/controller/CategoryPublicController.java
> +        return categoryPublicService.getCategories(from, size);
Вот смотри, контроллер называется CategoryPublicController, в приннципе понятно что он работает с категориями, можно уже категорию не упоминать в имени метода. И так понятно, но кода меньше. Та же история с сервисом :)

2023-02-22 04:57 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/request/service/RequestService.java
> +        if (requestRepository.findRequestByRequesterIdAndEventId(userId, eventId).isPresent()) {
Тут паверно все лучше использовать exists-метод (как ниже уже сделано)
как то так
existsByRequesterIdAndEventId

Иначе мы достаем ненужные далее данные из БД, плюс объект Optional, не очень оптимально выглядит :)

2023-02-22 04:57 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/user/service/UserAdminService.java
> +    public void deleteUser(Long id) {
А давай ка еще над все методы, которые изменяют данные (insert, update и delete) будем оформлять как логические транзакции, так будет правильнее. То есть добавим аннотацию @Transactional над ними.
На методе выше он есть, тут тоже хотелось бы, удаление же

2023-02-22 06:42 UTC, pavlovAndrei commented on ewm-service/src/main/java/ru/practicum/ewm/category/controller/CategoryPublicController.java
> +        return categoryPublicService.getCategories(from, size);
Поменял названия

2023-02-22 13:54 UTC, pavlovAndrei commented on ewm-service/src/main/java/ru/practicum/ewm/category/controller/CategoryAdminController.java
> +    public void deleteCategory(@Positive @PathVariable Long catId) {
Убрал

2023-02-22 14:11 UTC, pavlovAndrei commented on ewm-service/src/main/java/ru/practicum/ewm/user/service/UserAdminService.java
> +    public void deleteUser(Long id) {
добавил аннотации

2023-02-22 14:12 UTC, pavlovAndrei commented on ewm-service/src/main/java/ru/practicum/ewm/request/service/RequestService.java
> +        if (requestRepository.findRequestByRequesterIdAndEventId(userId, eventId).isPresent()) {
добавил/помянял методы на exist, где это было через получение optional

2023-02-22 14:17 UTC, pavlovAndrei commented
> Привет, Андрей, спасибо за PR
> 
> В целом все хорошо, единственное, предлоду вот что - посмотреть имена методов сервисов и убрать лишние упоминания сущности. Напрмер, сравни
> 
> `usertService.updateUser(user)` или `usertService.update(user)`
> 
> Второй вариант как то проще читать как мне кажется, как думаешь? Для контроллеров не так важно, мы эти методы сами напрямую не вызываем в коде =)
> 
> Еще подумай, пожалуйста, не слишком ли много try-catch в коде, не портит ли это читаемость кода, может лучше делать обычные проверки кодом перед тем как произвести действие, а потом ловить еще исключение, но это на подумать :)



> Привет, Андрей, спасибо за PR
> 
> В целом все хорошо, единственное, предлоду вот что - посмотреть имена методов сервисов и убрать лишние упоминания сущности. Напрмер, сравни
> 
> `usertService.updateUser(user)` или `usertService.update(user)`
> 
> Второй вариант как то проще читать как мне кажется, как думаешь? Для контроллеров не так важно, мы эти методы сами напрямую не вызываем в коде =)
> 
> Еще подумай, пожалуйста, не слишком ли много try-catch в коде, не портит ли это читаемость кода, может лучше делать обычные проверки кодом перед тем как произвести действие, а потом ловить еще исключение, но это на подумать :)

трайкетчи тоже поменял на валидации кодом/добавил где надо методы в репозитории

2023-02-22 16:53 UTC, eugene-lenkevich commented
> трайкетчи тоже поменял на валидации кодом/добавил где надо методы в репозитории

круто, я думал что до этого руки уже не дойдут :)

2023-02-22 16:56 UTC, eugene-lenkevich approved these changes
Теперь все отлично, спасибо :)

2023-02-22 18:16 UTC, merged