Added feature functionality (comments)
pavlovAndrei/java-explore-with-me pull request #3
Opened 2023-02-23 22:04 UTC by pavlovAndrei

2023-02-23 22:14 UTC, pavlovAndrei commented
И снова здравствуйте! )) Доделал работу над фичей Комментарии. В постман коллекцию добавил все существующие тесты (которые были для проверки main) и в коллекцию добавил 2 каталога с моими проверками, в конце. Жду результатов проверки!

2023-02-24 06:08 UTC, eugene-lenkevich requested changes
Привет, Андрей, спасибо за PR

Здоровски, мне очень нравится код, единственное хотелось переименовать один метод чтобы совсем гут было :)

2023-02-24 06:08 UTC, eugene-lenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/comment/controller/CommentAdminController.java
> +        log.debug("Received the request to delete comment with id: {}", commentId);
Кстати, эти отладочные логи можно и не писать ручками, а собирать автоматически, как то вот так
https://stackoverflow.com/questions/33744875/spring-boot-how-to-log-all-requests-and-responses-with-exceptions-in-single-pl

но то fyi :)

2023-02-24 06:08 UTC, eugene-lenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/comment/mapper/CommentMapper.java
> +    CommentDto toCommentDto(Comment comment);
В имени класса уже есть Comment, в имени метода это наименование можно опустить без потери читаемости, как думаешь?

Например вот так

`CommentDto toDto(Comment comment)`

2023-02-24 06:08 UTC, eugene-lenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/comment/model/Comment.java
> +    @ManyToOne(fetch = FetchType.EAGER, optional = false)
fetch = FetchType.EAGER и так же для этой связи по умолчанию идет, можно лишний раз не указывать :)

2023-02-24 06:08 UTC, eugene-lenkevich commented on ewm-service/src/main/resources/schema.sql
> +    comment   VARCHAR(500) NOT NULL,
500 символов для комментария не особо много, вообще можно не указывать размерность, просто  varchar или text типы указать. Тогда у нас будет CLOB-поле, не особо в курсе какое оно по размеру именно в постгре, но это как минимум 2Гб, все с запасом влезет :)

2023-02-24 07:10 UTC, pavlovAndrei commented on ewm-service/src/main/resources/schema.sql
> +    comment   VARCHAR(500) NOT NULL,
Я тут специально так указал, хотя думаю, что не имело смысла, т.к. у меня в DTO модели тоже стоит ограничение на 500 симвлолов. Я сделал это как фичей, чтобы большие комменты нельзя было комментить. А тут просто для аналогии проставил)

2023-02-24 07:11 UTC, eugene-lenkevich commented on ewm-service/src/main/resources/schema.sql
> +    comment   VARCHAR(500) NOT NULL,
ок, я не заметил)

2023-02-24 07:11 UTC, pavlovAndrei commented on ewm-service/src/main/java/ru/practicum/ewm/comment/controller/CommentAdminController.java
> +        log.debug("Received the request to delete comment with id: {}", commentId);
Хорошо, я обязательно потом почитаю.

2023-02-24 07:13 UTC, pavlovAndrei commented
Евгений, я правильно понял, что ты принял проект и эти комментарии не критичные и просто для размышелания? просто, я после принятия проекта не могу залить новую версию (практикум не дает)

2023-02-24 07:22 UTC, pavlovAndrei commented on ewm-service/src/main/java/ru/practicum/ewm/comment/mapper/CommentMapper.java
> +    CommentDto toCommentDto(Comment comment);
да, согласен

2023-02-24 07:23 UTC, pavlovAndrei commented on ewm-service/src/main/java/ru/practicum/ewm/comment/model/Comment.java
> +    @ManyToOne(fetch = FetchType.EAGER, optional = false)
и тут все ты правильно заметил

2023-02-24 11:34 UTC, merged